### ISSUE TITLE
Transfer to the JuliaHealth organization?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaNeuroscience/NIfTI.jl#37]
Any objection to moving this repo to the JuliaHealth organization?

cc: @Tokazama 
cc: @simonster 
cc: @notZaki
cc: @ViralBShah

See also: https://github.com/JuliaIO/DICOM.jl/issues/48

**Comment by Tokazama** [comment]
I'm fine with this. It will actually probably be good to have an org where it could get more attention.

**Comment by Tokazama** [comment]
I should also note that I made JuliaNeuroscience that may be a more appropriate place for it

**Comment by DilumAluthge** [comment]
Either seems fine! I agree that a more domain-specific org will be better for it than the IO org.

I've added JuliaNeuroscience to the list (https://juliahealth.org/related-organizations/) which will hopefully also increase discoverability.

**Comment by tknopp** [comment]
Whatever is decided: DICOM.jl and NIfTI.jl should be in the same organization.

**Comment by DilumAluthge** [comment]
DICOM.jl now lives in JuliaHealth: https://github.com/JuliaHealth/DICOM.jl

We'd be happy to accept NIfTI.jl into JuliaHealth.

Let me know if you want to be added as a member of JuliaHealth, or if you need additional permissions to transfer repositories.

**Comment by ViralBShah** [comment]
Go for it!

**Comment by tknopp** [comment]
I think @Tokazama should make the final decision. I am just here as user that regularly looks by here to wait until @Tokazama awesome overhauled implementation lands to master.

**Comment by Tokazama** [comment]
My only hesitation with transferring it to JuliaHealth is that it NIfTI is a neuro specific format that isn't commonly used outside of research. If JulaiHealth includes any physiologically related package then the  GIFTI and CIFTI formats as well as the 10+ neurophysiology related formats should be supported by packages under JuliaHealth. I know that the the JuliaHealth description says "We use the Julia programming language to improve medicine, health care, public health, and biomedical research.", but if thats broad enough to include any biologically derived data then most of BioJulia will should be in JuliaHealth. 

Now with all that said, if that really is the intention of JuliaHealth and it's best for the future of these packages I'm in favor of moving it to JuliaHealth.

**Comment by tknopp** [comment]
I use NifTI as a general replacement for DICOM in the context of tomographic imaging, independent if neuro or not (but I am of course aware of the origins of NIfTI). So JuliaHealth is fine IMHO.
Independent of the organization I am more eagerly waiting that this package actually gets into a better shape, which is once your work lands ;-)

**Comment by DilumAluthge** [comment]
@Tokazama It's entirely up to you!

> My only hesitation with transferring it to JuliaHealth is that it NIfTI is a neuro specific format that isn't commonly used outside of research.

Based on this description, probably the repo would be better suited for JuliaNeuroscience?

**Comment by DilumAluthge** [comment]
> @Tokazama It's entirely up to you!
> 
> > My only hesitation with transferring it to JuliaHealth is that it NIfTI is a neuro specific format that isn't commonly used outside of research.
> 
> Based on this description, probably the repo would be better suited for JuliaNeuroscience?

I do think it will fit better in JuliaNeuroscience than JuliaIO.

That way you can centralize all of the neuroscience research-specific file formats in JuliaNeuroscience.

**Comment by Tokazama** [comment]
Sounds good. I don't think I have permissions to transfer repos from JuliIO. Do I need to give someone someone permissions for JuliaNeuroscience?

**Comment by Tokazama** [comment]
@tknopp , I think you have owner permissions for this repo. Would you like me to provide you with access to JuliaNeuroscience so that you can transfer the repo?

**Comment by tknopp** [comment]
I can do so

**Comment by tknopp** [comment]
done :-)

**Comment by tknopp** [comment]
I actually have no rights to close this anymore :-) @Tokazama Habe you rights?

**Comment by Tokazama** [comment]
Thanks! You should also have write access now too.
